<a href="https://colab.research.google.com/github/fedluk/Kebulew/blob/master/Numpy_Slicing_and_Indexing_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Import Numpy

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3]).shape # 3 columns 1 row

(3,)

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,9]]).shape # 3 columns 3 rows

(3, 3)

In [ ]:
np.array([[7,8,9,19,11],[3,4,5,6,7]])

array([[ 7,  8,  9, 19, 11],
       [ 3,  4,  5,  6,  7]])

In [ ]:
np.array([[7,8,9,19,11],[3,4,5,6,7]]).shape

(2, 5)

#### Bracket indexing and selection

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

#### broadcasting

In [ ]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### 2d array indexing

In [ ]:
arr2 = np.arange(0,25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr2[1][4]

9

In [ ]:
arr2[2:,2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

#### Selection

In [ ]:
arr = np.arange(0,11) 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [ ]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# Great Job !